import pandas as pd
cars = pd.read_csv("cars.csv")
print("First five rows with odd numbered columns")
print()
print(cars.iloc[:5,0::2])
print()
print("Row that contains the Model of Mazda RX4")
print()
print(cars.loc[cars['Model'] == "Mazda RX4"])
print()
print("Cylinders of Camaro Z28")
print()
print(cars.loc[cars['Model'] == "Camaro Z28",["Model","cyl"]])
print()
print("Cylinders and gear of : Mazda RX4 Wag, Ford Pantera L, Honda Civic")
print()
print(cars.loc[cars['Model'].isin(["Mazda RX4 Wag","Ford Pantera L","Honda Civic"]),["Model","cyl","gear"]])
input()

